//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaTech
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2256_DBEntities : DbContext
    {
        public PI2256_DBEntities()
            : base("name=PI2256_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dobavljac> dobavljacs { get; set; }
        public virtual DbSet<inventura> inventuras { get; set; }
        public virtual DbSet<lijek> lijeks { get; set; }
        public virtual DbSet<narudzbenica> narudzbenicas { get; set; }
        public virtual DbSet<racun> racuns { get; set; }
        public virtual DbSet<skladisna_primka> skladisna_primka { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<stavka_inventure> stavka_inventure { get; set; }
        public virtual DbSet<stavka_narudzbe> stavka_narudzbe { get; set; }
        public virtual DbSet<stavka_primke> stavka_primke { get; set; }
        public virtual DbSet<stavka_racuna> stavka_racuna { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<uloga> ulogas { get; set; }
        public virtual DbSet<zaposlenik> zaposleniks { get; set; }
    }
}
