//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class lijek
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lijek()
        {
            this.stavka_inventure = new HashSet<stavka_inventure>();
            this.stavka_narudzbe = new HashSet<stavka_narudzbe>();
            this.stavka_primke = new HashSet<stavka_primke>();
            this.stavka_racuna = new HashSet<stavka_racuna>();
        }
    
        public int id_lijek { get; set; }
        public string naziv_lijek { get; set; }
        public string jedinica_mjere { get; set; }
        public string rok_trajanja { get; set; }
        public string nacin_primjene { get; set; }
        public string potreban_recept { get; set; }
        public double cijena { get; set; }
        public double nabavna_cijena { get; set; }
        public int kolicina_na_zalihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_inventure> stavka_inventure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_narudzbe> stavka_narudzbe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_primke> stavka_primke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stavka_racuna> stavka_racuna { get; set; }
    }
}
