//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaTech
{
    using System;
    using System.Collections.Generic;
    
    public partial class zaposlenik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zaposlenik()
        {
            this.inventuras = new HashSet<inventura>();
            this.narudzbenicas = new HashSet<narudzbenica>();
            this.racuns = new HashSet<racun>();
            this.skladisna_primka = new HashSet<skladisna_primka>();
        }
    
        public int id_zaposlenik { get; set; }
        public string ime_prezime { get; set; }
        public int id_uloge { get; set; }
        public System.DateTime datum_rodenja { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string kontakt { get; set; }
        public int id_statusa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inventura> inventuras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<narudzbenica> narudzbenicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<racun> racuns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skladisna_primka> skladisna_primka { get; set; }
        public virtual status status { get; set; }
        public virtual uloga uloga { get; set; }
    }
}
